site_name: NLPInitiative
# 
site_author: ASU Fall-2024/Spring-2025 Capstone Group 8 with The J Healthcare Initiative
# 
nav:
  - About: 
    - About This Project: index.md
  - User Guide:
    - Data Importing and Normalization: notebooks/Data_Import_Notes.ipynb
    - Data Preprocessing and Tokenization: notebooks/Data_Processing.ipynb
    - Model Training, Evaluation and Deployment: notebooks/Model_Training.ipynb
    - Model Inference: notebooks/Inference_Demo.ipynb
  - Module Documentation:
    - Dataset Management: dataset-management.md
    - Model Training, Evaluation and Inference: model-management.md
  
extra_css:
  - style/style.css

theme:
  name: readthedocs

plugins:
- search
- mkdocs-jupyter
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy