site_name: NLPInitiative
# 
site_author: ASU Capstone Group 8 / J Healthcare Initiative
# 
nav:
  - Home: index.md
  - User Guide:
    - Data Importing and Normalization: notebooks/Data_Import_Notes.ipynb
    - Data Preprocessing and Tokenization: notebooks/Data_Processing.ipynb
    - Model Training, Evaluation and Deployment: notebooks/Model_Training.ipynb
    - Model Inference: notebooks/Inference_Demo.ipynb
  - Module Documentation:
    - Dataset Management: dataset-management.md
    - Model Training, Evaluation and Inference: model-management.md
  

theme:
  name: readthedocs

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
- mkdocs-jupyter